#!/usr/bin/env python3
"""Generate Adafruit-GFX (GLCD) font headers from a TrueType font.

The firmware draws the chart with the same font the server-side matplotlib
figure used (DejaVu Sans Bold) at the same pixel sizes, so the panel shows the
text the way it always looked instead of a substitute typeface.

Usage:
    python tools/make_gfx_font.py <font.ttf> <pixel-size> <symbol-name> <out.h>

The generated header matches the layout of Adafruit's own fontconvert output
(bitmaps array, glyph table, GFXfont struct), so it can be parsed by the same
tooling and dropped into a sketch.

Glyph metrics follow the GFXfont convention measured from Adafruit's fonts:
`xOffset`/`yOffset` are relative to the cursor, which sits on the text baseline,
and each glyph's bitmap is a continuous MSB-first bit stream that is padded to a
byte boundary before the next glyph starts ("bitmapOffset" is a byte offset).
"""

import sys

from PIL import Image, ImageDraw, ImageFont

FIRST_CHAR = 0x20
LAST_CHAR = 0x7E
INK_LEVEL = 128


def render_glyphs(ttf_path, pixel_size):
    font = ImageFont.truetype(ttf_path, pixel_size)
    ascent, descent = font.getmetrics()
    glyphs = []

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        char = chr(code)
        advance = int(round(font.getlength(char)))
        box = font.getbbox(char)

        if box is None or box[2] <= box[0] or box[3] <= box[1]:
            # Space and other blank glyphs carry no bitmap at all.
            glyphs.append({"bits": [], "width": 0, "height": 0,
                           "advance": advance, "x": 0, "y": 0})
            continue

        left, top, right, bottom = box
        width, height = right - left, bottom - top
        image = Image.new("L", (width, height), 0)
        ImageDraw.Draw(image).text((-left, -top), char, font=font, fill=255)
        pixels = image.load()
        bits = [1 if pixels[x, y] >= INK_LEVEL else 0
                for y in range(height) for x in range(width)]

        glyphs.append({"bits": bits, "width": width, "height": height,
                       "advance": advance, "x": left, "y": top - ascent})

    return glyphs, ascent, descent


def pack_bitmaps(glyphs):
    """Concatenate every glyph's bits, padding each one to a byte boundary."""
    data = bytearray()
    bit_index = 0
    for glyph in glyphs:
        glyph["offset"] = len(data)  # byte offset, as GFXfont expects
        for bit in glyph["bits"]:
            if bit_index % 8 == 0:
                data.append(0)
            if bit:
                data[-1] |= 0x80 >> (bit_index % 8)
            bit_index += 1
        if bit_index % 8:  # pad the glyph out to a whole byte
            bit_index += 8 - (bit_index % 8)
    return data


def emit_header(name, glyphs, bitmaps, y_advance, source, pixel_size):
    lines = [
        "// Generated by tools/make_gfx_font.py - do not edit by hand.",
        f"// {source} at {pixel_size}px em, the size the matplotlib figure used.",
        "#pragma once",
        "#include <Adafruit_GFX.h>",
        "",
        f"const uint8_t {name}Bitmaps[] PROGMEM = {{",
    ]

    for i in range(0, len(bitmaps), 12):
        row = ", ".join(f"0x{byte:02X}" for byte in bitmaps[i:i + 12])
        lines.append("  " + row + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")

    for index, glyph in enumerate(glyphs):
        char = chr(FIRST_CHAR + index)
        label = "' '" if char == " " else char
        lines.append(
            f"  {{ {glyph['offset']:5d}, {glyph['width']:2d}, {glyph['height']:2d},"
            f" {glyph['advance']:2d}, {glyph['x']:4d}, {glyph['y']:4d} }},"
            f"  // 0x{FIRST_CHAR + index:02X} {label}"
        )
    lines.append("};")
    lines.append("")
    lines.append(f"const GFXfont {name} PROGMEM = {{")
    lines.append(f"    (uint8_t *){name}Bitmaps, (GFXglyph *){name}Glyphs,")
    lines.append(f"    0x{FIRST_CHAR:02X}, 0x{LAST_CHAR:02X}, {y_advance}}};")
    lines.append("")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 5:
        print(__doc__)
        return 1

    ttf_path, pixel_size, name, out_path = (
        sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4])
    glyphs, ascent, descent = render_glyphs(ttf_path, pixel_size)
    bitmaps = pack_bitmaps(glyphs)

    import os
    source = os.path.basename(ttf_path)
    with open(out_path, "w") as handle:
        handle.write(emit_header(name, glyphs, bitmaps, ascent + descent,
                                 source, pixel_size))

    caps = [g for g in glyphs if g["height"] > 0]
    print(f"{name}: {len(bitmaps)} bytes of bitmaps, {len(glyphs)} glyphs, "
          f"ascent={ascent} descent={descent} yAdvance={ascent + descent}")
    print(f"  tallest glyph: {max(g['height'] for g in caps)}px, "
          f"lowest descender: {max(0, max(-g['y'] + g['height'] - 1 - ascent for g in caps))}px")
    for text in ("NASDAQ FUTURES", "CSI Dividend Low Volatility 100", "29,843.25", "+0.30%"):
        width = sum(glyphs[ord(c) - FIRST_CHAR]["advance"] for c in text)
        print(f"  {text!r:34s} advance width {width}px")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
